<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-05T16:53:31 IST" name="Suite" finished-at="2024-01-05T16:54:28 IST" duration-ms="57645">
    <groups>
      <group name="errorValidation">
        <method signature="ErrorValidationTests.loginErrorValidation()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" name="loginErrorValidation" class="FW24.Tests.ErrorValidationTests"/>
      </group> <!-- errorValidation -->
    </groups>
    <test started-at="2024-01-05T16:53:31 IST" name="Error Validation" finished-at="2024-01-05T16:54:25 IST" duration-ms="54647">
      <class name="FW24.Tests.ErrorValidationTests">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:53:31 IST" name="launchApplication" finished-at="2024-01-05T16:53:47 IST" duration-ms="15832" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="cartProductErrorValidation()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:53:47 IST" name="cartProductErrorValidation" finished-at="2024-01-05T16:53:51 IST" duration-ms="4482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:53:51 IST" name="tearDown" finished-at="2024-01-05T16:53:52 IST" duration-ms="631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:53:52 IST" name="launchApplication" finished-at="2024-01-05T16:54:05 IST" duration-ms="12992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:54:05 IST" name="loginErrorValidation" finished-at="2024-01-05T16:54:06 IST" duration-ms="1542" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or passwor] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or passwor] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at FW24.Tests.ErrorValidationTests.loginErrorValidation(ErrorValidationTests.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:54:06 IST" name="tearDown" finished-at="2024-01-05T16:54:07 IST" duration-ms="666" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:54:07 IST" name="launchApplication" finished-at="2024-01-05T16:54:20 IST" duration-ms="13150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:54:20 IST" name="loginErrorValidation" finished-at="2024-01-05T16:54:23 IST" duration-ms="2883" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or passwor] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or passwor] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at FW24.Tests.ErrorValidationTests.loginErrorValidation(ErrorValidationTests.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FW24.Tests.ErrorValidationTests@4b14918a]" started-at="2024-01-05T16:54:24 IST" name="tearDown" finished-at="2024-01-05T16:54:25 IST" duration-ms="1361" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- FW24.Tests.ErrorValidationTests -->
    </test> <!-- Error Validation -->
    <test started-at="2024-01-05T16:53:31 IST" name="Submit Order" finished-at="2024-01-05T16:54:28 IST" duration-ms="57645">
      <class name="FW24.Tests.SubmitOrderTests">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:53:32 IST" name="launchApplication" finished-at="2024-01-05T16:53:48 IST" duration-ms="15633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:53:48 IST" name="submitOrder" data-provider="getData" finished-at="2024-01-05T16:53:53 IST" duration-ms="5620" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sachin@123, email=sachin.waghmare@gmail.com, productName=IPHONE 13 PRO}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:53:53 IST" name="tearDown" finished-at="2024-01-05T16:53:54 IST" duration-ms="1003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:53:54 IST" name="launchApplication" finished-at="2024-01-05T16:54:06 IST" duration-ms="11586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:54:06 IST" name="submitOrder" data-provider="getData" finished-at="2024-01-05T16:54:11 IST" duration-ms="5024" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sachin@123, email=sachin.waghmare123@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:54:11 IST" name="tearDown" finished-at="2024-01-05T16:54:12 IST" duration-ms="1052" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:54:12 IST" name="launchApplication" finished-at="2024-01-05T16:54:26 IST" duration-ms="13608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistory()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:54:26 IST" name="orderHistory" finished-at="2024-01-05T16:54:28 IST" depends-on-methods="FW24.Tests.SubmitOrderTests.submitOrder" duration-ms="2229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FW24.Tests.SubmitOrderTests@1a20270e]" started-at="2024-01-05T16:54:28 IST" name="tearDown" finished-at="2024-01-05T16:54:28 IST" duration-ms="536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- FW24.Tests.SubmitOrderTests -->
    </test> <!-- Submit Order -->
  </suite> <!-- Suite -->
</testng-results>
